### PR TITLE
feat: AST job pack

### PR DESCRIPTION
**Pull request by Vayhyr**
preview: 
preview

### CODE REVIEW

**Comment by DomGrieco** [comment]
This looks nice. @Kanubiz sign off before merge

**Comment by jdsmith2816** [comment]
I'll look this over in a bit but please squash commits before opening PR;  should just be one with something like "feat: added AST job pack"

**Review by Kanubiz — APPROVED** [review]
already merged it

**Review by Kanubiz — CHANGES_REQUESTED** [review]
there is an issue with a DrawDot function in the hudwindow

**Pull request merged**
