### PR TITLE
DRK Improvements

### PR DESCRIPTION
**Pull request by poly1k**
[DRK](https://youtu.be/nb6ivlkG2P4 "DelvUI DRK")

**User Features:**
- Add toggles to all bars
ffxiv_dx11_4hRKeiGvcX
- Make Dark Arts proc. prettier
- Update configuration layout
- Fix mana chunk padding
- Add Living Shadow bar (disabled by default)
- Add optional mana overflow display (>9000)
ffxiv_dx11_PaGzpmkgDC

**Internal:**
- DRY Blood Gauge draw code

### CODE REVIEW

**Comment by DomGrieco** [comment]
Looks good!

**Comment by Kanubiz** [comment]
Updated your branch with the current state of main

**Review by Kanubiz — CHANGES_REQUESTED** [review]
You forgot the mana bar chunks at 3k 6k 9k

**Comment by poly1k** [comment]
> You forgot the mana bar chunks at 3k 6k 9k

Added the mana overflow thing in the latest commit :)

**Review by DomGrieco — APPROVED** [review]
Looks good!

**Pull request merged**
